### ISSUE TITLE
Please add support for HS256

### ISSUE THREAD

**Issue by faxm0dem** [haproxytech/haproxy-lua-jwt#11]
Hi,

First of all thanks for this project, and the excellent [documentation](https://www.haproxy.com/blog/using-haproxy-as-an-api-gateway-part-2-authentication/). We're trying to use keycloak with this setup, and are having problems because of the default signing algorithm:

```
[debug] 328/151714 (32616) : RS256 supported. Incorrect alg in JWT: HS256
[debug] 328/151714 (32616) : Algorithm not valid.
[debug] 328/151714 (32616) : req.authorized = false
```

Would it be possible to support HS256 ?

**Comment by NickMRamirez** [comment]
It should be possible, but I will need to read the luaossl docs to see how. https://raw.githubusercontent.com/wahern/luaossl/master/doc/luaossl.pdf

**Comment by NickMRamirez** [comment]
@faxm0dem I've added logic to support HS256. You will need to add a line to your HAProxy config in the `global` section:

```
setenv OAUTH_HMAC_SECRET <your secret key here>
```

Please let me know if this works for you.

**Comment by faxm0dem** [comment]
I just tested it and it works as expected !
Thanks a bunch for your quick action !
