### ISSUE TITLE
licence inconsistency ?

### ISSUE THREAD

**Issue by xens** [haproxytech/haproxy-lua-jwt#6]
I saw that you switched the licence from GPLv2 to the Apache License 2.0 recently https://github.com/haproxytech/haproxy-lua-jwt/blob/master/LICENSE. But your code there https://github.com/haproxytech/haproxy-lua-jwt/blob/master/lib/jwtverify.lua still references GPLv2, so I'm wondering which one I should use for my work based on this repo not void one or the other.

**Comment by NickMRamirez** [comment]
Good catch. It should be Apache v2. I will change update the Lua file.

**Comment by NickMRamirez** [comment]
Fixed in commit b2200990ab66f207ea7439eb908a8aa1071e4f50

**Comment by xens** [comment]
Awesome thanks !
